### ISSUE TITLE
Improve Github Action Scripts in Extensions

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-release#547]
**Description:**
Recently, when I reached the Github Support for a different issue, they pointed out the following improvements we can do the workflows of our extensions,

1. Use the latest set up java action and checkout action step
> For the first one, they're using setup-java@v1 I recommend moving over to @v2 + using the adopt distribution. It can used cached versions of java that are already pre-installed on the image so it should be faster + it will have better logging + eliminate any chance for a download error.

Recommended action step,
```
- name: Checkout Repository
  uses: actions/checkout@v2
- name: Set up JDK 11
  uses: actions/setup-java@v2
  with:
    distribution: 'adopt'
    java-version: '11'
```

2. Streamline dependency repositories configuration
> I noticed that in your build.gradle file, you're using multiple maven elements.
> https://github.com/ballerina-platform/ballerina-openapi/blob/master/build.gradle#L72-L92
> It's actually possible (and preferable) to replace these with a single element for all repos. When downloading packages, the repo section is ignored. This means you can replace all of the maven elements with one like this:

Recommended,
```
        maven {
            url = 'https://maven.pkg.github.com/ballerina-platform/*'
            credentials {
                username System.getenv('packageUser')
                password System.getenv('packagePAT')
            }
        }
```
